/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// `Env` is generated by `wrangler types` from the bindings in wrangler.jsonc
// (DB: D1Database, COVERS: R2Bucket, ASSETS, CF_ACCESS_* vars). Re-run
// `pnpm exec wrangler types` after editing wrangler.jsonc.
type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

declare namespace App {
    // Exposes `Astro.locals.runtime.env.DB` / `.COVERS` in pages, endpoints
    // and middleware, both in `astro dev` (via platformProxy) and in prod.
    interface Locals extends Runtime {}
}
